---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spc-deploy
  labels:
    app: spc
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: spc
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: spc-pod
      labels:
        app: spc
    spec:
      containers:
        - name: spc1
          image: sonarnew.jfrog.io/spc-docker/spc:1.9
          ports:
            - containerPort: 8080
              protocol: TCP
                      

