---
apiVersion: v1
kind: Service
metadata:
  name: spc-svc
  labels:
    app: spc
spec:
  selector:
    app: spc
  type: LoadBalancer
  ports:
    - port: 33000
      targetPort: 8080
      protocol: TCP

  
    