---
- name: deploy the spring pet clinic
  hosts: all
  become: yes
  tasks:
    - name: Install latest version of "openjdk-11-jdk"
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: latest
    - name: jar file download from JFrog
      ansible.builtin.get_url:
        url: https://spc8.jfrog.io/artifactory/spc-libs-release-local/org/springframework/samples/spring-framework-petclinic/5.3.22/spring-framework-petclinic-5.3.22.war
        dest: /home/devops
        url_username: namgaddasatish@gmail.com
        url_password: AKCp8nH4kN6e5h4GCDCuLepuBL36jCwweysoaGdhJxXdfYEWfybquygQrAb78ryLshFY53Z2kGh1
    - name: Copy the service file
      ansible.builtin.copy:
        src: /home/ubuntu/remote_root/remote_root/workspace/spc/spring-petclinic.service
        dest: /etc/systemd/system/spring-petclinic.service
    - name: Restart spc service file
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: spring-petclinic.service